name: Deploy Netlify

on: 
  push: 
    branches: 
      - main
    paths:
      - "src/**"
      - ".github/workflows/deploy.yml"
      - "public/**"

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Repository Checkout
          uses: actions/checkout@v4
        
        - name: Setup PNPM
          uses: pnpm/action-setup@v4
          with:
            version: 10

        - name: Setup Nodejs
          uses: actions/setup-node@v4
          with: 
            node-version: 20
            cache: "pnpm"

        - name: Install Netlify Cli
          run: pnpm add netlify-cli@17.10.1 -g

          # pnpm ci
        - name: Install Dependencies
          run: pnpm install --frozen-lockfile

        - name: Generate Build
          run: pnpm run build

        - name: Deploy to Netlify
          id: netlify_deploy
          run: |
            prod_flag=""
            if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
            netlify deploy \
              --dir dist \
              --site ${{secrets.NETLIFY_SITE_ID}} \
              --auth ${{secrets.NETLIFY_API_TOKEN}} \
              $prod_flag